CREATE TABLE public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    event TEXT NOT NULL,
    properties JSONB,
    timestamp TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- No RLS needed for this table if it's only written to from a service_role key function.
-- But we grant access to service_role just in case.
GRANT ALL ON TABLE public.analytics_events TO service_role;
