// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogalytywmafaztluhjzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nYWx5dHl3bWFmYXp0bHVoanpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTUzMzEsImV4cCI6MjA2NTU3MTMzMX0.Xrc4aKFsarDQw4-4GFWrWU4RvtmIc7kVfPgaruAsd94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);